name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Clasp Token
      uses: namaggarwal/clasp-token-action@v0.0.1
      with:
        client-id: "$CLASP_CLIENT_ID"
        client-secret: "$CLASP_CLIENT_SECRET"
        refresh-token: "$CLASP_REFRESH_TOKEN"

    - name: Deploy to Google Apps Script
      run: |
        npm install -g @google/clasp
        npm run build
        clasp push        